# secrets (Secretos en Settings → Secrets → Actions)
name: ctx-secrets
on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Usar secreto en un comando
        env:
          TOKEN: ${{ secrets.API_KEY }}
        run: |
          echo "Tengo un token secreto y no se mostrará su valor"
          # ejemplo real: curl -H "Authorization: Bearer $TOKEN" https://api.ejemplo.com/ping
      - name: Llamada a API (directo)
        run: |
          curl -H "Authorization: Bearer ${{ secrets.API_KEY }}" https://api.ejemplo.com/ping
